apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sport-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # Init container waits for MySQL to be ready
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL at $DB_HOST:$DB_PORT..."
              until nc -z $DB_HOST $DB_PORT; do
                echo "MySQL not ready yet, sleeping 3s..."
                sleep 3
              done
              echo "MySQL is up!"
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"

      containers:
        - name: backend
          image: rohit7669/sport-backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: sports_center
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root