apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sport-app

spec:

  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: rohit7669/sport-backend:latest

        ports:
        - containerPort: 8081

        env:

        - name: DB_HOST
          value: mysql

        - name: DB_PORT
          value: "3306"

        - name: DB_NAME
          value: sports_center

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: root