apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sport-ingress
  namespace: sport-app

spec:
  ingressClassName: nginx

  rules:

  - host: sport.local

    http:

      paths:

      - path: /
        pathType: Prefix

        backend:
          service:
            name: frontend
            port:
              number: 80