version: "3.9"

services:

  backend:
    image: rohit7669/sport-backend:latest
    container_name: sport-backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    networks:
      - sport-network

  frontend:
    image: rohit7669/sport-frontend:latest
    container_name: sport-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sport-network

  mysql:
    image: mysql:8.0
    container_name: sports-center-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sports-center
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sport-network

  redis:
    image: redis:7-alpine
    container_name: sports-center-redis-container
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - sport-network

volumes:
  mysql-data:
  redis-data:

networks:
  sport-network:
    driver: bridge
