name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]   # CI workflow names
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest backend image..."
            docker pull rohit7669/sport-backend:latest

            echo "Pulling latest frontend image..."
            docker pull rohit7669/sport-frontend:latest

            echo "Stopping old containers if they exist..."
            docker stop sport-backend sport-frontend || true
            docker rm sport-backend sport-frontend || true

            echo "Running backend container..."
            docker run -d --name sport-backend \
              --network sport-network \
              -p 8081:8081 \
              rohit7669/sport-backend:latest

            echo "Running frontend container..."
            docker run -d --name sport-frontend \
              --network sport-network \
              -p 80:80 \
              rohit7669/sport-frontend:latest
